In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [2]:
x1data=[70, 90, 88, 95, 75]#3
x2data=[80, 88, 90, 98, 65]#4
x3data=[75, 93, 90, 100, 70]#5월 모의고사
ydata=[150, 185, 180, 200, 140] #수능점수
#예측값[149.75005 185.1799  180.01122 198.90154 141.55467

In [5]:
x1=tf.placeholder(tf.float32)
x2=tf.placeholder(tf.float32)
x3=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
w1=tf.Variable(tf.random_normal([1]), name="weight1")
w2=tf.Variable(tf.random_normal([1]), name="weight2")
w3=tf.Variable(tf.random_normal([1]), name="weight3")
b=tf.Variable(tf.random_normal([1]), name="bias")

In [6]:
hf=x1*w1+x2*w2+x3*w3+b
cost=tf.reduce_mean(tf.square(hf-y))

In [8]:
train=tf.train.GradientDescentOptimizer(1e-5).minimize(cost)
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(2001):
    cv, hv, _ =sess.run([cost, hf, train],
             feed_dict={x1:x1data,x2:x2data,x3:x3data,y:ydata})
    if step % 10==0:
        print(step, "cost:",cv,"prediction:",hv)

0 cost: 2.75306 prediction: [148.50406 185.53757 179.86792 198.59412 143.04048]
10 cost: 2.7323108 prediction: [148.51338 185.53484 179.86903 198.59633 143.02953]
20 cost: 2.7117066 prediction: [148.52267 185.5321  179.87013 198.59857 143.01862]
30 cost: 2.6913097 prediction: [148.53189 185.52939 179.87122 198.60075 143.00774]
40 cost: 2.6710937 prediction: [148.54109 185.52669 179.87231 198.60295 142.99693]
50 cost: 2.6510358 prediction: [148.55023 185.52399 179.87338 198.60512 142.98615]
60 cost: 2.6311388 prediction: [148.55936 185.5213  179.87447 198.6073  142.97542]
70 cost: 2.611422 prediction: [148.56844 185.51865 179.87553 198.60947 142.96474]
80 cost: 2.5918427 prediction: [148.57747 185.51599 179.8766  198.61165 142.95409]
90 cost: 2.5724614 prediction: [148.58647 185.51334 179.87767 198.61378 142.9435 ]
100 cost: 2.553251 prediction: [148.59543 185.51073 179.87874 198.61592 142.93295]
110 cost: 2.5341702 prediction: [148.60435 185.50809 179.87978 198.61806 142.92244]
120 cos

1120 cost: 1.2461275 prediction: [149.33174 185.29721 179.96446 198.79514 142.0598 ]
1130 cost: 1.238087 prediction: [149.33745 185.29558 179.9651  198.79655 142.05295]
1140 cost: 1.2301167 prediction: [149.34314 185.29395 179.96574 198.79796 142.04613]
1150 cost: 1.2222031 prediction: [149.34882 185.29233 179.9664  198.79938 142.03934]
1160 cost: 1.2143694 prediction: [149.35448 185.29076 179.96706 198.8008  142.0326 ]
1170 cost: 1.2065866 prediction: [149.36008 185.28914 179.96768 198.8022  142.02585]
1180 cost: 1.198889 prediction: [149.36568 185.28755 179.96834 198.8036  142.01917]
1190 cost: 1.1912448 prediction: [149.37125 185.28595 179.96895 198.80498 142.01248]
1200 cost: 1.1836776 prediction: [149.37677 185.28436 179.96957 198.80634 142.00583]
1210 cost: 1.1761564 prediction: [149.38231 185.2828  179.97021 198.80774 141.99922]
1220 cost: 1.1686869 prediction: [149.38782 185.28125 179.97084 198.80914 141.99263]
1230 cost: 1.161302 prediction: [149.3933  185.2797  179.97147 198.

In [ ]:
#행렬로 데이터 표현


In [21]:
xdata=[[70, 90, 88, 95, 75],
[80, 88, 90, 98, 65],
[75, 93, 90, 100, 70]]#5월 모의고사
ydata=[150, 185, 180, 200, 140] #수능점수

In [22]:
np.shape(xdata) #(3,5)->(5,3)
xdata=np.transpose(xdata)

In [28]:
np.shape(xdata) 
ydata=[[150], [185], [180], [200], [140]]
np.shape(ydata)

(5, 1)

In [29]:
x=tf.placeholder(tf.float32, shape=[None,3])
y=tf.placeholder(tf.float32, shape=[None,1])
w=tf.Variable(tf.random_normal([3,1]), name="weight")
b=tf.Variable(tf.random_normal([1]), name="bias")

In [31]:
#hf=x*w+b 이렇게 쓰면 안됨
hf=tf.matmul(x,w)+b
cost=tf.reduce_mean(tf.square(hf-y))
train=tf.train.GradientDescentOptimizer(1e-5).minimize(cost)

In [32]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [34]:
for step in range(2001):
    cv, hv, _ =sess.run([cost, hf, train],
             feed_dict={x:xdata,y:ydata})
    if step % 10==0:
        print(step, "cost:",cv,"prediction:",hv)

0 cost: 40329.414 prediction: [[-22.46519 ]
 [-30.286322]
 [-29.794104]
 [-31.449036]
 [-27.249537]]
10 cost: 6.695943 prediction: [[153.93408]
 [182.18958]
 [180.30423]
 [198.27728]
 [137.34596]]
20 cost: 6.205459 prediction: [[154.51045]
 [182.9044 ]
 [181.00471]
 [199.04277]
 [137.91054]]
30 cost: 6.165932 prediction: [[154.4991 ]
 [182.91132]
 [181.0052 ]
 [199.04285]
 [137.9267 ]]
40 cost: 6.126735 prediction: [[154.48582]
 [182.91582]
 [181.00334]
 [199.04039]
 [137.94095]]
50 cost: 6.0878463 prediction: [[154.4726 ]
 [182.92032]
 [181.00148]
 [199.0379 ]
 [137.95514]]
60 cost: 6.0493193 prediction: [[154.45944]
 [182.92479]
 [180.99965]
 [199.03548]
 [137.96927]]
70 cost: 6.011102 prediction: [[154.44633]
 [182.92923]
 [180.99779]
 [199.03304]
 [137.98334]]
80 cost: 5.9731874 prediction: [[154.43327]
 [182.93369]
 [180.99596]
 [199.0306 ]
 [137.99733]]
90 cost: 5.935566 prediction: [[154.42026]
 [182.93811]
 [180.99411]
 [199.02818]
 [138.01126]]
100 cost: 5.89828 prediction: [[

1210 cost: 3.2019153 prediction: [[153.25726]
 [183.34164]
 [180.8263 ]
 [198.8214 ]
 [139.23987]]
1220 cost: 3.187079 prediction: [[153.24911]
 [183.34454]
 [180.82506]
 [198.82002]
 [139.2483 ]]
1230 cost: 3.1723416 prediction: [[153.24098]
 [183.34743]
 [180.82385]
 [198.81868]
 [139.2567 ]]
1240 cost: 3.157759 prediction: [[153.23291]
 [183.35031]
 [180.82266]
 [198.81732]
 [139.26508]]
1250 cost: 3.1432438 prediction: [[153.22484]
 [183.3532 ]
 [180.82146]
 [198.81596]
 [139.2734 ]]
1260 cost: 3.1288767 prediction: [[153.21681]
 [183.35603]
 [180.82024]
 [198.81462]
 [139.2817 ]]
1270 cost: 3.1146152 prediction: [[153.20883]
 [183.3589 ]
 [180.81906]
 [198.81331]
 [139.28995]]
1280 cost: 3.1004736 prediction: [[153.20088]
 [183.36174]
 [180.81787]
 [198.812  ]
 [139.29817]]
1290 cost: 3.086429 prediction: [[153.19296]
 [183.3646 ]
 [180.81671]
 [198.8107 ]
 [139.30637]]
1300 cost: 3.0725026 prediction: [[153.18506]
 [183.3674 ]
 [180.8155 ]
 [198.80937]
 [139.31451]]
1310 cost: 3.

In [38]:

xy=np.loadtxt("test-score.csv", delimiter=',', dtype=np.float32)
xy
#xdata:1~3열, ydata:4열
#100, 70, 102 => 예상
#60,70,100 => 예상
#80,90,95 => 예상
#cost출력



array([[ 80.,  79.,  77., 149.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [40]:
import matplotlib.pyplot as plt
from tensorflow import keras
import tensorflow as tf
import numpy as np
import pandas as pd
 
print(tf.__version__)
 
data = np.loadtxt("test-score.csv",delimiter = ',', dtype = np.float32)
 
xdata = data[:,0:3]
ydata = data[:,3].reshape(-1,1)
 
x = tf.placeholder(tf.float32, shape = (None, 3))
y = tf.placeholder(tf.float32, shape = (None, 1))
 
w = tf.Variable(tf.random.normal([3,1]), name = "weight")
b = tf.Variable(tf.random.normal([1]), name = 'bias')
 
hf = x @ w + b
cost = tf.reduce_mean(tf.square(hf - y)) 
 
train = tf.train.GradientDescentOptimizer(1e-5).minimize(cost)
 
sess = tf.Session()
sess.run(tf.global_variables_initializer())
 
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict = {x : xdata , y : ydata})
    
    if step == 2000:
        print(step, "cost : ", cv, "prediction : ", hv)
 
test = np.transpose([[100, 70, 102],#142
                     [60, 70, 100], #162
                     [80, 90, 95] ]) #195
 
for data in test:
    print(sess.run(hf, feed_dict = {x : data.reshape(-1,3) }))

1.14.0
2000 cost :  12.478937 prediction :  [[156.73138 ]
 [182.36389 ]
 [181.90567 ]
 [199.19221 ]
 [137.05191 ]
 [102.13685 ]
 [151.9201  ]
 [116.708694]
 [170.69292 ]
 [160.06113 ]
 [143.92532 ]
 [140.34505 ]
 [186.7555  ]
 [153.38345 ]
 [152.06828 ]
 [186.49576 ]
 [143.37625 ]
 [184.06369 ]
 [178.55772 ]
 [160.43243 ]
 [177.1492  ]
 [172.40897 ]
 [168.96512 ]
 [154.00551 ]
 [189.19873 ]]
[[142.49887]]
[[162.07227]]
[[195.80533]]


In [41]:
from sklearn.model_selection import train_test_split

In [45]:
x,y=np.arange(10).reshape((5,2)), range(5)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
list(y)

[0, 1, 2, 3, 4]

In [58]:
xtrain, xtest, ytrain, ytest=train_test_split(x,y, test_size=0.33, random_state=42)
print(xtrain)
print(xtest)

[[4 5]
 [0 1]
 [6 7]]
[[2 3]
 [8 9]]


In [60]:
x=np.array([[10., -10., 1],
          [5., 0., 2.],
           [15., 10., 22.]])
x

array([[ 10., -10.,   1.],
       [  5.,   0.,   2.],
       [ 15.,  10.,  22.]])

In [66]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit_transform(x)
scaler.transform(x)

array([[0.5       , 0.        , 0.        ],
       [0.        , 0.5       , 0.04761905],
       [1.        , 1.        , 1.        ]])

In [67]:
QUEUE_LENGTH=20
q=tf.FIFOQueue(QUEUE_LENGTH, "float")

In [68]:
enq_ops=q.enqueue_many(([1.0,2.0,3.0,4.0],))
qr=tf.train.QueueRunner(q, [enq_ops, enq_ops, enq_ops])

W0730 13:45:13.104734 12036 deprecation.py:323] From <ipython-input-68-3a20a306f6a6>:2: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [70]:
sess=tf.Session()
coord=tf.train.Coordinator()
threads=qr.create_threads(sess, coord=coord, start=True)

for step in range(30):
    print(sess.run(q.dequeue()))

coord.request_stop() #스레드 정지
coord.join(threads) #정지될때까지 기다리는 함수

1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0


In [71]:
QUEUE_LENGTH=20
q=tf.FIFOQueue(QUEUE_LENGTH, "float")
enq_ops1=q.enqueue_many(([1.0,2.0,3.0,4.0],))
enq_ops2=q.enqueue_many(([5.0,6.0,7.0,8.0],))
enq_ops3=q.enqueue_many(([9.0,10.0,11.0,12.0],))
qr=tf.train.QueueRunner(q, [enq_ops1, enq_ops2, enq_ops3])

In [76]:
sess=tf.Session()
coord=tf.train.Coordinator()
threads=qr.create_threads(sess, coord=coord, start=True)

for step in range(30):
    print(sess.run(q.dequeue()))

coord.request_stop() #스레드 정지
coord.join(threads) #정지될때까지 기다리는 함수

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
1.0
2.0
3.0
4.0
9.0
10.0
11.0
12.0
5.0
6.0
7.0
8.0
1.0
2.0


In [ ]:
#파일에서 데이터 읽기 작업 순서
# 1. 파일 목록 읽기
# 2. 파일 목록을 파일이름큐에 저장
# 3. reader가 파일이름큐에서 파일명을 하나씩 읽어온다
# 4. decoder는 파일에 있는 데이터를 읽어들인다
# 5. 데이터를 정제(전처리)
# 6. 정제된 데이터를 example queue에 저장
# 7. 학습 진행


In [ ]:
queue=tf.train.string_input_producer(['q_1.txt','q_2.txt','q_3.txt'], shuffle=False)
coord=tf.train.Coordinator()

In [ ]:
sess=tf.Session()
reader=tf.TextLineReader()
key, value=reader.read(queue=queue)
print(sess.run(key))
print(sess.run(value))

In [ ]:
for i in range(100):
    speed, distance=tf.decode_csv(value,record_defaults=[[0],[0]])
   #print(sess.run([speed, distance]))
coord.request_stop() #스레드 정지
coord.join(threads) 