In [44]:
import tensorflow as tf
import numpy as np
import pandas as pd
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [45]:
def MyScaler(data): #MinMaxScaling
    #print(np.min(data)) #전체 data 최소값
    de=np.max(data,axis=0)-np.min(data,axis=0) #열 단위 최소값
    num=data-np.min(data,axis=0)
    return num/de   
    #print(np.min(data,axis=1)) #행 단위 최소값

In [47]:
xy=MyScaler(xy)
print(xy)
#xy.shape #(8, 5)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [48]:
xdata=xy[:, 0:-1]
xdata.shape#(8, 4)
ydata=xy[:, [-1]]

In [49]:
x=tf.placeholder(tf.float32, shape=[None, 4])
y=tf.placeholder(tf.float32, shape=[None, 1])
w=tf.Variable(tf.random_normal([4,1]))
b=tf.Variable(tf.random_normal([1]))

In [50]:
hf=tf.matmul(x,w)+b
cost=tf.reduce_mean(tf.square(hf-y))

In [57]:
train=tf.train.GradientDescentOptimizer(1e-6).minimize(cost)

In [58]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(101):
    cv,hv,_=sess.run([cost, hf, train], feed_dict={x:xdata, y:ydata})
    print(step, "cost:", cv, "hf:", hv)

0 cost: 1.5710654 hf: [[ 0.12956904]
 [-1.6079597 ]
 [-0.9644265 ]
 [-0.19784652]
 [-0.5517199 ]
 [-0.47120303]
 [-0.44249564]
 [-0.710333  ]]
1 cost: 1.571055 hf: [[ 0.12957472]
 [-1.6079538 ]
 [-0.9644217 ]
 [-0.19784287]
 [-0.55171555]
 [-0.47119886]
 [-0.44249278]
 [-0.71033   ]]
2 cost: 1.5710446 hf: [[ 0.12958045]
 [-1.607948  ]
 [-0.96441686]
 [-0.19783919]
 [-0.5517112 ]
 [-0.47119462]
 [-0.44248992]
 [-0.71032715]]
3 cost: 1.571034 hf: [[ 0.12958619]
 [-1.607942  ]
 [-0.964412  ]
 [-0.19783553]
 [-0.5517067 ]
 [-0.47119036]
 [-0.44248703]
 [-0.71032417]]
4 cost: 1.5710236 hf: [[ 0.12959193]
 [-1.6079361 ]
 [-0.96440715]
 [-0.19783185]
 [-0.5517023 ]
 [-0.4711861 ]
 [-0.44248408]
 [-0.7103212 ]]
5 cost: 1.571013 hf: [[ 0.12959766]
 [-1.6079302 ]
 [-0.9644023 ]
 [-0.19782823]
 [-0.55169797]
 [-0.47118187]
 [-0.44248128]
 [-0.7103183 ]]
6 cost: 1.5710027 hf: [[ 0.1296034 ]
 [-1.6079242 ]
 [-0.9643975 ]
 [-0.19782455]
 [-0.5516936 ]
 [-0.47117764]
 [-0.44247836]
 [-0.71031535]]
7 

In [60]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
#y값은 one hot 인코딩 방식으로 초기화 함...(a,b,c)중 하나를 hot하게 함...
y_data = [[0, 0, 1],#2
          [0, 0, 1],#2
          [0, 0, 1],#2
          [0, 1, 0],#1
          [0, 1, 0],#1
          [0, 1, 0],#1
          [1, 0, 0],#0
          [1, 0, 0]]#0

In [61]:
num_classes=3
x=tf.placeholder("float", [None,4])
y=tf.placeholder("float", [None,num_classes])
w=tf.Variable(tf.random_normal([4,num_classes]))
b=tf.Variable(tf.random_normal([num_classes]))
#hf=x*w+b
#[None,4],[4,3]+[3]=

In [62]:
hf=tf.nn.softmax(tf.matmul(x,w)+b)
cost=tf.reduce_mean(-tf.reduce_sum(y*tf.log(hf),axis=1))
train=tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [82]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict={x:x_data, y:y_data})
        if step % 200==0:
            print(step, sess.run(cost, feed_dict={x:x_data, y:y_data}))
    print("="*50)
#xdata= 1, 11, 7, 9   => y?
    res=sess.run(hf, feed_dict={x:[[1, 11, 7, 9 ]]})
    print(sess.run(tf.argmax(res, axis=1)))
    print("="*50)
    
    res2=sess.run(hf, feed_dict={x:[[1, 11, 7, 9 ],
                                   [1,3,4,3],
                                   [1,1,0,1]]})
    print(sess.run(tf.argmax(res2, axis=1)))    
    

0 8.506994
200 0.68822074
400 0.56815
600 0.47372437
800 0.384216
1000 0.29525173
1200 0.23215695
1400 0.21086007
1600 0.1930259
1800 0.17785762
2000 0.16481116
[1]
[1 0 2]


In [79]:
res

array([[1.0774668e-02, 9.8921645e-01, 8.8615579e-06]], dtype=float32)

In [96]:
xy=np.loadtxt('zoo.csv', delimiter=',', dtype=np.float32)
xy.shape #101,17
xdata=xy[:, 0:-1]
ydata=xy[:,[-1]]
xdata.shape
ydata.shape

(101, 1)

In [99]:
x=tf.placeholder(tf.float32, [None, 16])
y=tf.placeholder(tf.int32, [None, 1])
y_one_hot=tf.one_hot(y,7) # 3(y) -> 0001000(y_one_hot)
print("one_hot", y_one_hot)
y_one_hot=tf.reshape(y_one_hot, [-1,7])
print("one_hot after reshape", y_one_hot)

#one hot함수는 한 차원 높게 변환됨
#y: [[0], [3], ..., [5]]=> [None,1] 의 shape
#one_hot =>
#[[[1000000]], [[0001000]], ..., [[00000100]]] => [None, 1, 7]
#우리가 바라는 출력 결과의 모습은 [None,7] 임.
#reshape을 하면 됨. tf.shape(y_one_hot, [-1, 7])코딩하면
#[None,7]로 reshape 됨.
#[[[1000000]], [[0001000]]...] => [[1000000], [0001000]...] 


#0~6 :7가지 종류의 동물 -> 분류기 7개
#w1x1+w2x2+...w7x7+b => softmax => 0번 종류의 동물에 대한 확률
#w1x1+w2x2+...w7x7+b => softmax => 1번 종류의 동물에 대한 확률
#..
##w1x1+w2x2+...w7x7+b => softmax => 6번 종류의 동물에 대한 확률

#1000000, 0100000... => [None,7]

one_hot Tensor("one_hot_9:0", shape=(?, 1, 7), dtype=float32)
one_hot after reshape Tensor("Reshape_9:0", shape=(?, 7), dtype=float32)


In [103]:
w=tf.Variable(tf.random_normal([16, 7]))
b=tf.Variable(tf.random_normal([7]))
#x:[None,16], w:[16,7]
logit= tf.matmul(x,w)+b
hf=tf.nn.softmax(logit)
cost=tf.nn.softmax_cross_entropy_with_logits(logits=logit,
                                             labels=y_one_hot)
cost2=tf.reduce_mean(cost)
train=tf.train.GradientDescentOptimizer(0.1).minimize(cost2)
prediction=tf.argmax(hf,1)
correct_prediction= tf.equal(prediction,tf.argmax(y_one_hot,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [108]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={x:xdata, y:ydata})
        if step % 100==0:
            cv, av=sess.run([cost2, accuracy], feed_dict={x:xdata, y:ydata})
            print("step:", step, "cost:",cv, "acc:", av)
#전체 데이터로 트레이닝 수행하여 모델 생성
#모델에 전체 데이터를 집어 넣어서 정확도 출력
#데이터를 분할하지 않았음
    pred=sess.run(prediction, feed_dict={x:xdata})
    for p , y in zip(pred, ydata.flatten()):
   

step: 0 cost: 4.5739946 acc: 0.05940594
step: 100 cost: 0.852849 acc: 0.8019802
step: 200 cost: 0.5455036 acc: 0.8910891
step: 300 cost: 0.40911326 acc: 0.9009901
step: 400 cost: 0.32320789 acc: 0.9009901
step: 500 cost: 0.2625727 acc: 0.9207921
step: 600 cost: 0.21792191 acc: 0.95049506
step: 700 cost: 0.18449779 acc: 0.97029704
step: 800 cost: 0.15909556 acc: 0.97029704
step: 900 cost: 0.13939986 acc: 0.97029704
step: 1000 cost: 0.12379706 acc: 0.97029704
step: 1100 cost: 0.11118772 acc: 0.97029704
step: 1200 cost: 0.100818306 acc: 0.990099
step: 1300 cost: 0.0921617 acc: 1.0
step: 1400 cost: 0.08484002 acc: 1.0
step: 1500 cost: 0.07857621 acc: 1.0
step: 1600 cost: 0.07316323 acc: 1.0
step: 1700 cost: 0.068443276 acc: 1.0
step: 1800 cost: 0.06429441 acc: 1.0
step: 1900 cost: 0.06062106 acc: 1.0
step: 2000 cost: 0.057347354 acc: 1.0
step: 2100 cost: 0.054412562 acc: 1.0
step: 2200 cost: 0.05176731 acc: 1.0
step: 2300 cost: 0.049371194 acc: 1.0
step: 2400 cost: 0.047191016 acc: 1.0
ste