In [1]:
import numpy as np
import pandas as pd
#레벤슈타인 알고리즘
def calc_distance(a, b):
    #같으면 0
    if a == b:
        return 0
    #문자열 길이
    a_len = len(a)
    b_len = len(b)
    
    if a == "":
        return b_len
    if b == "":
        return a_len
    # matrix를 하나씩 크게 설정 및 초기화
    matrix = [[] for i in range(a_len+1)]
    for i in range(a_len+1):
        matrix[i] = [0 for k in range(b_len+1)]
    for i in range(a_len+1):
        matrix[i][0] = i
    for k in range(b_len+1):
        matrix[0][k] = k
       
    for i in range(1, a_len+1):  
        #코스트를 0으로 초기화
        cost=0
        aw=a[i-1]
        for k in range(1, b_len+1):
            #문자열을 검색해서 같으면 cost가 0, 다르면 1로 설정
            bw=b[k-1]
            if aw==bw:
                cost = 0
            else:
                cost = 1

            matrix[i][k] = min([
                matrix[i-1][k]+1,#삽입
                matrix[i][k-1]+1,#제거
                matrix[i-1][k-1]+cost,#변경
                
            ])
            print(matrix[i]," || " ,matrix[i][k])

    return matrix[a_len][b_len]#값 리턴


In [2]:
class MulLayer:
    def __init__(self):
        self.x=None
        self.y=None
        
    def forward(self,x,y):
        self.x=x
        self.y=y
        out=x*y
        return out
    
    def backward(self,dout):   
        dx=dout*self.y
        dy=dout*self.x
        return dx,dy     

In [3]:
mal=MulLayer()
mtl=MulLayer()

In [4]:
apple=100
apple_num=2
tax=1.1
apple_price=mal.forward(apple,apple_num)
price=mtl.forward(apple_price, tax)
print("price:", int(price))

price: 220


In [21]:
dprice=1
dapple_price, dtax=mtl.backward(dprice)
print(dapple_price, dtax)
dapple_num,dapple, =mal.backward(dapple_price)
print(dapple, dapple_num, dtax)

1.1 200
110.00000000000001 2.2 200


In [6]:
#상수형(Constant)
import tensorflow as tf

In [7]:
a=tf.constant([5], dtype=tf.float32)
b=tf.constant([10], dtype=tf.float32)
c=tf.constant([2], dtype=tf.float32)
d=a*b+c

sess=tf.Session()
#sess.run(a)
print(sess.run(d))

[52.]


In [8]:
#세션을 생성해서 그래프 실행
#세션:그래프를 실행시켜주는 runner

In [9]:
#플레이스홀더:
data=[1,2,3,4]
x=tf.placeholder(dtype=tf.float32)
y=x*2
print(sess.run(y, feed_dict={x:data}))
#피딩(feeding):학습용 데이터를 딕셔너리 형태로 전달하는 행위(그래프를 실행하는 시점)


[2. 4. 6. 8.]


In [10]:
#변수(Variable):훈련(트레이닝, 모델링)과정에서 
#변화하는 기울기, 절편 등
#hf=wx+b
#hf=0.5x+2

In [11]:
inputData=[1,2,3]
x=tf.placeholder(dtype=tf.float32)
w=tf.Variable([2], dtype=tf.float32)
yhat=w*x
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)

sess.run(yhat, feed_dict={x:inputData})


array([2., 4., 6.], dtype=float32)

In [12]:
#tf.matmul( , ) 활용
x=tf.constant([[1,2,3]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
print(sess.run(y)[0][0])

12


In [13]:
x=tf.Variable([[1,2,3]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
init=tf.global_variables_initializer()
sess.run(init)
sess.run(y)

array([[12]])

In [14]:
#tf.matmul( , ) 활용
import numpy as np
x=tf.constant([[1,2,3]])
#w=tf.constant([[2],[2],[2]])
#x=tf.constant(np.array([1,2]))
sess.run(tf.transpose(x))
#sess.run(x)

array([[1],
       [2],
       [3]])

In [15]:
#None:아직 결정되지 않은 상태

In [16]:
#x=tf.Variable([[1,2,3],[1,2,3],[2,3,4]])
indata=[[1,2,3],[1,2,3],[2,3,4]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3])
w=tf.constant([[2],[2],[2]], dtype=tf.float32)
y=tf.matmul(x,w)#3*3 . 3*1  => 3*1
init=tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:indata}) #3행3열

array([[12.],
       [12.],
       [18.]], dtype=float32)

In [17]:
data=[[1,1,1],[2,2,2]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3])
w=tf.Variable([[2],[2],[2]],dtype=tf.float32)
b=tf.Variable([4], dtype=tf.float32)
y=tf.matmul(x,w)+b #2*3 3*1 => 2*1
# 1 1 1   2
# 2 2 2   2    => 6+4  10
#         2    => 12+4 16
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y, feed_dict={x:data})

array([[10.],
       [16.]], dtype=float32)

In [18]:
#1
apple=100
appleNum=2
orange=150
orangeNum=3
tax=1.1
#forward/backward

#*price출력:(100*2+150*3)*1.1
#dApple
#dappleNum
#dorange
#dorangeNum
#dtax

#2.구구단의 특정 단을 출력하는 함수 작성(placeholder사용)

In [19]:
#2.구구단의 특정 단을 출력하는 함수 작성(placeholder사용)

In [20]:
def googoo(dan):
    5*1=5
    5*9=45

SyntaxError: can't assign to operator (<ipython-input-20-1f873fc27f9c>, line 2)