In [1]:
import numpy as np

In [21]:
arr=np.array([np.arange(0,4*8)])

In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [48]:
v=arr.reshape([4,2,4])

In [50]:
v

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [41]:
myTensor=np.arange(2*3*4).reshape(2,3,4)
myTensor#(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
np.transpose(myTensor,[1,2,0]).shape

(3, 4, 2)

In [1]:
import tensorflow as tf

In [2]:
from tensorflow.examples.tutorials.mnist import input_data

In [3]:
mnist=input_data.read_data_sets("./mnist2/data",one_hot=True)

W0821 14:59:32.804894 21104 deprecation.py:323] From <ipython-input-3-baad7562b6fe>:1: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0821 14:59:32.810879 21104 deprecation.py:323] From C:\Users\Kyujin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
W0821 14:59:32.812872 21104 deprecation.py:323] From C:\Users\Kyujin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Plea

Extracting ./mnist2/data\train-images-idx3-ubyte.gz


W0821 14:59:33.181885 21104 deprecation.py:323] From C:\Users\Kyujin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
W0821 14:59:33.184881 21104 deprecation.py:323] From C:\Users\Kyujin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
W0821 14:59:33.249707 21104 deprecation.py:323] From C:\Users\Kyujin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future v

Extracting ./mnist2/data\train-labels-idx1-ubyte.gz
Extracting ./mnist2/data\t10k-images-idx3-ubyte.gz
Extracting ./mnist2/data\t10k-labels-idx1-ubyte.gz


In [4]:
learning_rate=0.001
total_epoch=30
batch_size=128

In [5]:
n_input=28 #가로픽셀수
n_step=28 #세로 픽셀수
n_hidden=128 # 히든 레이어
n_class=10

In [6]:
tf.reset_default_graph()
x=tf.placeholder(tf.float32, [None, n_step, n_input])
y=tf.placeholder(tf.float32,[None,n_class])
w=tf.Variable(tf.random_normal([n_hidden,n_class]))
b=tf.Variable(tf.random_normal([n_class]))

In [7]:
cell=tf.nn.rnn_cell.BasicRNNCell(n_hidden)
outputs, states=tf.nn.dynamic_rnn(cell, x, dtype=tf.float32)
outputs = tf.transpose(outputs,[1,0,2])
outputs=outputs[-1]
model= tf.matmul(outputs,w)+b




W0821 14:59:33.730422 21104 deprecation.py:323] From <ipython-input-7-84f6a6951c89>:1: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
W0821 14:59:33.732414 21104 deprecation.py:323] From <ipython-input-7-84f6a6951c89>:2: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0821 14:59:33.911933 21104 deprecation.py:506] From C:\Users\Kyujin\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to 

In [12]:
cost=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=y))
optimizer=tf.train.AdamOptimizer(learning_rate).minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [15]:
total_batch=int(mnist.train.num_examples/batch_size)
for epoch in range(total_epoch):
    total_cost=0
    for i in range(total_batch):
        batch_xs, batch_ys=mnist.train.next_batch(batch_size)
        batch_xs=batch_xs.reshape((batch_size, n_step, n_input))
        _, cv=sess.run([optimizer, cost], feed_dict={x:batch_xs, y:batch_ys})
        total_cost+=cv
    print("Epoch: " ,'%4d' %(epoch+1),
         'avg_cost=', '{:.3f}'.format(total_cost/total_batch))
is_correct=tf.equal(tf.argmax(model,1), tf.argmax(y,1) )
accuracy=tf.reduce_mean(tf.cast(is_correct, tf.float32))
test_batch_size=len(mnist.test.images)

test_xs=mnist.test.images.reshape(test_batch_size, n_step, n_input)
test_ys=mnist.test.labels
print('정확도:',sess.run(accuracy, feed_dict={x:test_xs, y:test_ys}))

Epoch:     1 avg_cost= 0.078
Epoch:     2 avg_cost= 0.081
Epoch:     3 avg_cost= 0.079
Epoch:     4 avg_cost= 0.067
Epoch:     5 avg_cost= 0.066
Epoch:     6 avg_cost= 0.080
Epoch:     7 avg_cost= 0.068
Epoch:     8 avg_cost= 0.070
Epoch:     9 avg_cost= 0.068
Epoch:    10 avg_cost= 0.064
Epoch:    11 avg_cost= 0.068
Epoch:    12 avg_cost= 0.061
Epoch:    13 avg_cost= 0.061
Epoch:    14 avg_cost= 0.064
Epoch:    15 avg_cost= 0.070
Epoch:    16 avg_cost= 0.063
Epoch:    17 avg_cost= 0.058
Epoch:    18 avg_cost= 0.057
Epoch:    19 avg_cost= 0.062
Epoch:    20 avg_cost= 0.056
Epoch:    21 avg_cost= 0.060
Epoch:    22 avg_cost= 0.054
Epoch:    23 avg_cost= 0.060
Epoch:    24 avg_cost= 0.055
Epoch:    25 avg_cost= 0.062
Epoch:    26 avg_cost= 0.055
Epoch:    27 avg_cost= 0.058
Epoch:    28 avg_cost= 0.049
Epoch:    29 avg_cost= 0.047
Epoch:    30 avg_cost= 0.048
정확도: 0.9699


In [16]:
char_arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g',
            'h', 'i', 'j', 'k', 'l', 'm', 'n',
            'o', 'p', 'q', 'r', 's', 't', 'u',
            'v', 'w', 'x', 'y', 'z']

In [17]:
num_dic={n:i for i,n in enumerate(char_arr)}
num_dic

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}