In [23]:
import tensorflow as tf
import numpy as np
import pandas as pd

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [24]:
def MyScaler(data):
#     print(np.min(data))
    de=np.max(data, axis=0) -np.min(data, axis=0)
    num=data-np.min(data,axis=0)
    return num/de

In [25]:
xy=MyScaler(xy)
xy

array([[1.        , 1.        , 0.        , 1.        , 1.        ],
       [0.70548491, 0.70439552, 1.        , 0.71881783, 0.83755792],
       [0.54412549, 0.50274824, 0.57608696, 0.60646801, 0.6606331 ],
       [0.33890353, 0.31368023, 0.10869565, 0.45989134, 0.43800918],
       [0.51436   , 0.4258239 , 0.30434783, 0.58504805, 0.42624401],
       [0.49556179, 0.4258239 , 0.31521739, 0.48131134, 0.49276137],
       [0.11436064, 0.        , 0.20652174, 0.22007776, 0.18597238],
       [0.        , 0.07747099, 0.5326087 , 0.        , 0.        ]])

In [26]:

xdata=xy[:,0:-1]
ydata=xy[:,[-1]]

In [27]:
x=tf.placeholder(tf.float32, shape=[None, 4])
y=tf.placeholder(tf.float32, shape=[None, 1])
w=tf.Variable(tf.random_normal([4,1]), name= 'weight')
b=tf.Variable(tf.random_normal([1]), name= 'bias')


In [28]:
hf=tf.matmul(x,w)+b
cost=tf.reduce_mean(tf.square(hf-y))

In [29]:
train=tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [30]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(101):
    cv, hv, _ =sess.run([cost, hf, train], feed_dict={x:xdata, y:ydata})
    print(step, "cost:", cv, "hf:", hf)

0 cost: 2.7797313 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
1 cost: 2.6237931 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
2 cost: 2.4792116 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
3 cost: 2.3451371 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
4 cost: 2.220783 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
5 cost: 2.1054237 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
6 cost: 1.9983859 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
7 cost: 1.8990476 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
8 cost: 1.806834 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
9 cost: 1.7212121 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
10 cost: 1.6416904 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
11 cost: 1.5678134 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
12 cost: 1.4991591 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
13 cost: 1.4353389 hf: Tensor("add_1:0", shape=(?, 1), dtype=float32)
14 cost: 1.3759911 hf: Tensor("a

In [31]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
#y값은 one hot 인코딩 방식으로 초기화 함...(a,b,c)중 하나를 hot하게 함...
y_data = [[0, 0, 1],#2
          [0, 0, 1],#2
          [0, 0, 1],#2
          [0, 1, 0],#1
          [0, 1, 0],#1
          [0, 1, 0],#1
          [1, 0, 0],#0
          [1, 0, 0]]#0



In [32]:
x=tf.placeholder('float', [None,4])
y=tf.placeholder('float', [None,3])
w=tf.Variable(tf.random_normal([4,3]), name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

In [33]:
hf=tf.nn.softmax(tf.matmul(x,w)+b)
cost= tf.reduce_mean(-tf.reduce_sum(y*tf.log(hf),axis=1))

train=tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [40]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict={x:x_data, y:y_data})
        if step % 200 ==0:
            print(step, sess.run(cost, feed_dict={x:x_data, y:y_data}))
    print('='*50)
    res1=sess.run(hf, feed_dict={x:[[1,11,7,9],
                                  ]})
    res2=sess.run(hf, feed_dict={x:[[1,11,7,9],
                                  [1,3,4,3],
                                  [1,1,0,1]]})
    print(sess.run(tf.argmax(res2, axis=1)))

0 4.28997
200 0.7122805
400 0.62808025
600 0.55861974
800 0.49245855
1000 0.4264272
1200 0.3596577
1400 0.30144423
1600 0.28078175
1800 0.26421586
2000 0.24945742
[1 0 2]


In [42]:
xy=np.loadtxt('zoo.csv',delimiter=',', dtype=np.float32)
xy

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 3.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 6.],
       [0., 1., 1., ..., 0., 0., 1.]], dtype=float32)

In [43]:
xdata=xy[:,0:-1]
ydata=xy[:,[-1]]

In [49]:
x=tf.placeholder(tf.float32, [None,16])
y=tf.placeholder(tf.int64, [None,1])
y_one_hot=tf.one_hot(y,7)
print(y_one_hot)
y_one_hot=tf.reshape(y_one_hot, [-1,7])

Tensor("one_hot_4:0", shape=(?, 1, 7), dtype=float32)


In [59]:
w=tf.Variable(tf.random_normal([16,7]), name='weight')
b=tf.Variable(tf.random_normal([7]),name='bias')

logit=tf.matmul(x,w)+b
hf=tf.nn.softmax(logit)
cost=tf.nn.softmax_cross_entropy_with_logits(logits=logit, labels=y_one_hot)
cost2=tf.reduce_mean(cost)
train=tf.train.GradientDescentOptimizer(0.1).minimize(cost2)
prediction=tf.argmax(hf,1)
correct_prediction=tf.equal(prediction,tf.argmax(y_one_hot,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [62]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={x:xdata, y:ydata})
        if step % 100==0:
            cv,av=sess.run([cost2,accuracy], feed_dict={x:xdata, y:ydata})
            print("step: ", step, "cost:",cv, "accuracy:", av)
            
    pred=sess.run(prediction, feed_dict={x:xdata})
    for p , y in zip(pred, ydata.flatten()):
        print("[{}] 예측: {} 실제 y: {}". format(p==int(y), p, int(y)))

step:  0 cost: 4.901993 accuracy: 0.15841584
step:  100 cost: 0.688496 accuracy: 0.8118812
step:  200 cost: 0.4389216 accuracy: 0.8811881
step:  300 cost: 0.31830686 accuracy: 0.8910891
step:  400 cost: 0.24449442 accuracy: 0.9108911
step:  500 cost: 0.19656302 accuracy: 0.9405941
step:  600 cost: 0.16392495 accuracy: 0.980198
step:  700 cost: 0.14052987 accuracy: 0.980198
step:  800 cost: 0.12299037 accuracy: 0.980198
step:  900 cost: 0.1093642 accuracy: 0.990099
step:  1000 cost: 0.09847942 accuracy: 0.990099
step:  1100 cost: 0.08958964 accuracy: 1.0
step:  1200 cost: 0.08219683 accuracy: 1.0
step:  1300 cost: 0.0759554 accuracy: 1.0
step:  1400 cost: 0.07061788 accuracy: 1.0
step:  1500 cost: 0.0660025 accuracy: 1.0
step:  1600 cost: 0.061972607 accuracy: 1.0
step:  1700 cost: 0.058423735 accuracy: 1.0
step:  1800 cost: 0.05527468 accuracy: 1.0
step:  1900 cost: 0.05246134 accuracy: 1.0
step:  2000 cost: 0.049932495 accuracy: 1.0
step:  2100 cost: 0.047646876 accuracy: 1.0
step:  2