In [ ]:
import numpy as np
import pandas as pd


In [118]:
class MulLayer:
    def __init__(self):
        self.x=None
        self.y=None
        
    def forward(self,x,y):
        self.x=x
        self.y=y
        out= x* y
        return out
    def forward1(self,x,y):
        self.x=x
        self.y=y
        out = x+ y
        return out
    def backward(self,dout):
        dx=dout*self.y
        dy=dout*self.x
        return dx,dy
        


In [17]:
mal=MulLayer()
mtl=MulLayer()

In [102]:
apple=100
apple_num=2
tax=1.1
apple_price=mal.forward(apple,apple_num)
price=mtl.forward(apple_price,tax)
print("price: " , int(price))

price:  220


In [129]:
dprice=1
dtax,dapple_price =mtl.backward(dprice)
print(dapple_price, dtax)
dapple, dapple_num=mal.backward(dapple_price)
print(dapple,dapple_num,dtax)

650 1.1
1950 97500 1.1


상수형(Constant)


In [29]:
import tensorflow as tf

In [37]:
a=tf.constant([5],dtype=tf.float32)#상수를 저장하기 위한 데이터 타입
b=tf.constant([10], dtype=tf.float32)#상수를 저장하기 위한 데이터 타입
c=tf.constant([2], dtype=tf.float32)#상수를 저장하기 위한 데이터 타입
d=a*b+2
d

<tf.Tensor 'add_1:0' shape=(1,) dtype=float32>

In [39]:
sess=tf.Session()
sess.run(a)

array([5])

In [40]:
#플레이스 홀더
x=tf.placeholder(dtype=tf.float32)
y=x*2
sess.run(y,feed_dict={x:[1,2,3,4]})
#피딩(feeding): 학습용 데이터를 전달하는 행위


array([2., 4., 6., 8.], dtype=float32)

In [44]:
#변수(Variable):훈련 과정에서 변화하는 기울기, 절편 값을 변수라고 함
# hf=wx+b
inputData=[1,2,3]
x= tf.placeholder(dtype=tf.float32)
w=tf.Variable([2],dtype=tf.float32)
yhat=w*x
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(yhat, feed_dict={x:inputData})

array([2., 4., 6.], dtype=float32)

In [ ]:
#tf.matmul(x ,y) 행렬의 곱

In [57]:
inputData=np.array([[1,2,3],[1,2,3],[2,3,4]])
inputData2=np.array([2,2,3])
inputData2=inputData2.reshape(3,1)
x=tf.constant(inputData)
w=tf.constant(inputData2)
sess.run(tf.global_variables_initializer())

# print(inputData2)
y=tf.matmul(x,w)
sess.run(y)

array([[15],
       [15],
       [22]])

In [66]:
indata=[[1,2,3],[1,2,3],[2,3,4]]

x= tf.placeholder(dtype=tf.float32,shape=[None, 3])# data는 없으나 3행 3열의 행렬을 생성
w=tf.constant([[2],[2],[3]],dtype=tf.float32)
y=tf.matmul(x,w)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y, feed_dict={x:indata})

array([[15.],
       [15.],
       [22.]], dtype=float32)

In [65]:
data=[[1,1,1],[2,2,2]]
x=tf.placeholder(dtype=tf.float32,shape=[None,3])
w=tf.Variable([[2],[2],[2]],dtype=tf.float32)
b=tf.Variable([4],dtype=tf.float32)
y=tf.matmul(x,w)+b
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y, feed_dict={x:data})

array([[10.],
       [16.]], dtype=float32)

In [67]:
apple= 100
appleNum=2
orange=150
orangeNum=3
tax=1.1

In [119]:
malQ=MulLayer()
molQ=MulLayer()
molPQ=MulLayer()
mtlQ=MulLayer()

In [124]:
applePrice=malQ.forward(apple,appleNum)
orangePrice=molQ.forward(orange,orangeNum)
price=molPQ.forward1(applePrice,orangePrice)
price=mtlQ.forward(price,tax)
print(price)

715.0000000000001


In [121]:
# price=priceA+priceO

In [134]:
dprice=1
dtax, dprice_all=mtlQ.backward(dprice)
print(dprice_all,dtax)
dorangePrice,dapplePrice, = molPQ.backward(dtax)
print(dapplePrice,dorangePrice)
dorangeNum, dorange = molQ.backward(dtax)
print(dorangeNum, dorange)
dappleNum, dapple = malQ.backward(dtax)
print(dappleNum, dapple)

650 1.1
220.00000000000003 495.00000000000006
3.3000000000000003 165.0
2.2 110.00000000000001


In [ ]:
n = int(input())
indata=[[n]*9]
print(indata)
indata2=np.array([[i]for i in range(1, 10)])

print(indata2)


# x= tf.placeholder(dtype=tf.float32,shape=[None, 9])# data는 없으나 3행 3열의 행렬을 생성
# w=tf.constant(indata2,dtype=tf.float32)
# y=tf.matmul(x,w)
# sess=tf.Session()
# sess.run(tf.global_variables_initializer())
# sess.run(y, feed_dict={x:indata})